#!/bin/bash 
echo "Каталоги:"
  ls -la  -- "$1" | grep "d[rwx\-]\{9\}\."
echo  "Обычные файлы:"
  ls -la -- "$1" | grep "\-[rwx\-]\{9\}\."
echo "Символьные ссылки:"
 ls -la -- "$1" | grep  "l[rwx\-]\{9\}\."
echo  "Символьне устройства:"
 ls -la -- "$1" | grep "c[rwx\-]\{9\}\."
echo   "Блочные устройства:"
 ls -la -- "$1" | grep "b[rwx\-]\{9\}\."
